### ISSUE TITLE
Remove Device what no longer exist SHC1 V1

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#85] opened 2024-02-21 08:58 UTC
### System Health details

does nothing remove.

i had yesterday replaced 2 PSD with 2 Tasmota Devices.
Removed correctly in Livisi.

in the Integration, both Device still exist. 

Reboot or reload does not help

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by planbnet** [comment] 2024-02-21 10:47
You need to remove the entites assigned to the device first.
Closed as duplicate of #82

**Closed by planbnet** 2024-02-21 10:47 UTC
